<a href="https://colab.research.google.com/github/agrawalsajal02/ML_workshop/blob/master/Amazon_classification_Word_embedding_uniform_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implementation of the convolutional neural network (CNN) on the spam dataset. You have to go through the code and understand how a CNN model can be implemented in the case of the text. You repeat this implementation with the given datasets in Dataset folder.

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
cd /content/drive/My Drive/AI-ML_mine

/content/drive/My Drive/AI-ML_mine


In [0]:
import pandas as pd
data  = pd.read_csv('amazon_cells_labelled.txt', sep = '\t', names = ['text', 'class'])

In [0]:
text = data['text']
class_label = data['class']

In [0]:
class_label

0      0
1      1
2      1
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: class, Length: 1000, dtype: int64

In [0]:
text

0      So there is no way for me to plug it in here i...
1                            Good case, Excellent value.
2                                 Great for the jawbone.
3      Tied to charger for conversations lasting more...
4                                      The mic is great.
                             ...                        
995    The screen does get smudged easily because it ...
996    What a piece of junk.. I lose more calls on th...
997                         Item Does Not Match Picture.
998    The only thing that disappoint me is the infra...
999    You can not answer calls with the unit, never ...
Name: text, Length: 1000, dtype: object

In [0]:
import numpy as np
from keras.utils.np_utils import to_categorical
label = to_categorical(np.asarray(class_label))

Using TensorFlow backend.


In [0]:
label

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
from keras.preprocessing.text import Tokenizer
tk=Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',lower=True, split=" ")
tk.fit_on_texts(text)
index=tk.word_index
#print(index)
x = tk.texts_to_sequences(text)
#print (x)
vocab_size = len(index)

In [0]:
print(vocab_size+1)

1879


In [0]:
index

{'the': 1,
 'i': 2,
 'and': 3,
 'it': 4,
 'is': 5,
 'a': 6,
 'this': 7,
 'to': 8,
 'phone': 9,
 'my': 10,
 'for': 11,
 'of': 12,
 'not': 13,
 'with': 14,
 'very': 15,
 'great': 16,
 'was': 17,
 'on': 18,
 'in': 19,
 'that': 20,
 'good': 21,
 'have': 22,
 'you': 23,
 'product': 24,
 'quality': 25,
 'had': 26,
 'headset': 27,
 'works': 28,
 'battery': 29,
 'but': 30,
 'as': 31,
 'sound': 32,
 'so': 33,
 'are': 34,
 'well': 35,
 'one': 36,
 'all': 37,
 'use': 38,
 'ear': 39,
 'has': 40,
 'would': 41,
 'work': 42,
 'from': 43,
 'your': 44,
 'like': 45,
 'be': 46,
 'me': 47,
 'case': 48,
 'if': 49,
 'than': 50,
 "i've": 51,
 "don't": 52,
 'no': 53,
 'excellent': 54,
 'up': 55,
 'time': 56,
 "it's": 57,
 'after': 58,
 'price': 59,
 'recommend': 60,
 'does': 61,
 'really': 62,
 '2': 63,
 'at': 64,
 'or': 65,
 'best': 66,
 'out': 67,
 'only': 68,
 'service': 69,
 'get': 70,
 'when': 71,
 'nice': 72,
 "i'm": 73,
 'also': 74,
 'too': 75,
 'just': 76,
 'any': 77,
 'new': 78,
 'love': 79,
 'these'

In [0]:
x[0]

[33,
 117,
 5,
 53,
 214,
 11,
 47,
 8,
 155,
 4,
 19,
 337,
 19,
 1,
 546,
 416,
 2,
 241,
 190,
 6,
 812]

In [0]:
text[0]

'So there is no way for me to plug it in here in the US unless I go by a converter.'

In [1]:
from keras.preprocessing.sequence import pad_sequences
embedding_vecor_length =32
padded_docs = pad_sequences(x, maxlen=embedding_vecor_length, padding='post')
print (padded_docs[0].shape)

Using TensorFlow backend.


NameError: ignored

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padded_docs, label, test_size=0.30, random_state=42)

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Embedding
from keras.layers import Conv1D, GlobalMaxPooling1D, MaxPooling1D
from keras.utils.vis_utils import plot_model
model = Sequential()
model.add(Embedding(input_dim = vocab_size + 1, output_dim = 100,input_length=embedding_vecor_length))
model.add(Conv1D(filters = 128,kernel_size=3, activation='relu'))
model.add(MaxPooling1D(5))
model.add(Flatten())
model.add(Dense(256, activation = 'relu'))
model.add(Dense(2, activation = 'softmax'))
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
model.summary()









Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 32, 100)           187900    
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 30, 128)           38528     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 6, 128)            0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 768)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               196864    
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 514       
Total params: 423,80

In [0]:
model.fit(X_train, y_train, validation_data = (X_test, y_test),
              epochs=10,batch_size=100, verbose=2)




Train on 700 samples, validate on 300 samples
Epoch 1/10





 - 15s - loss: 0.6989 - acc: 0.4829 - val_loss: 0.7030 - val_acc: 0.4867
Epoch 2/10
 - 0s - loss: 0.6759 - acc: 0.5829 - val_loss: 0.6861 - val_acc: 0.5433
Epoch 3/10
 - 0s - loss: 0.6407 - acc: 0.7357 - val_loss: 0.6721 - val_acc: 0.5800
Epoch 4/10
 - 0s - loss: 0.5651 - acc: 0.7914 - val_loss: 0.6233 - val_acc: 0.6433
Epoch 5/10
 - 0s - loss: 0.4132 - acc: 0.9186 - val_loss: 0.5249 - val_acc: 0.7600
Epoch 6/10
 - 0s - loss: 0.2190 - acc: 0.9771 - val_loss: 0.4395 - val_acc: 0.7767
Epoch 7/10
 - 0s - loss: 0.0799 - acc: 0.9929 - val_loss: 0.4255 - val_acc: 0.8067
Epoch 8/10
 - 0s - loss: 0.0232 - acc: 0.9986 - val_loss: 0.4927 - val_acc: 0.8167
Epoch 9/10
 - 0s - loss: 0.0060 - acc: 1.0000 - val_loss: 0.5638 - val_acc: 0.8067
Epoch 10/10
 - 0s - loss: 0.0027 - acc: 1.0000 - val_loss: 0.6134 - val_acc: 0.8033


In [0]:
predictions_test = model.predict(X_test)


In [0]:
predictions_test

array([[5.55730164e-01, 4.44269866e-01],
       [2.78834581e-01, 7.21165419e-01],
       [5.67918736e-03, 9.94320750e-01],
       [9.99973178e-01, 2.67843479e-05],
       [1.60413363e-03, 9.98395860e-01],
       [7.44721501e-06, 9.99992609e-01],
       [9.99920249e-01, 7.97225584e-05],
       [4.29345220e-01, 5.70654750e-01],
       [9.99972224e-01, 2.78257721e-05],
       [1.28147341e-02, 9.87185299e-01],
       [3.33160599e-04, 9.99666810e-01],
       [9.99984622e-01, 1.53480469e-05],
       [7.92224586e-01, 2.07775384e-01],
       [4.00316626e-01, 5.99683344e-01],
       [5.88286994e-03, 9.94117141e-01],
       [8.96343172e-01, 1.03656843e-01],
       [1.36754272e-04, 9.99863267e-01],
       [9.99979973e-01, 2.00588474e-05],
       [2.41337288e-02, 9.75866258e-01],
       [2.18724716e-03, 9.97812748e-01],
       [7.56300928e-04, 9.99243736e-01],
       [3.93659361e-02, 9.60634053e-01],
       [6.97717624e-05, 9.99930263e-01],
       [3.15278977e-01, 6.84721053e-01],
       [9.999225

In [0]:
predictions_test1 = np.zeros_like(predictions_test)
predictions_test1[np.arange(len(predictions_test)), predictions_test.argmax(1)] = 1

In [0]:
predictions_test1

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions_test1))

              precision    recall  f1-score   support

           0       0.78      0.82      0.80       146
           1       0.82      0.79      0.80       154

   micro avg       0.80      0.80      0.80       300
   macro avg       0.80      0.80      0.80       300
weighted avg       0.80      0.80      0.80       300
 samples avg       0.80      0.80      0.80       300



In [0]:
spam_data = pd.read_csv('SMSSpamCollection', sep = '\t', encoding = 'latin', names = ['class','text']) 

In [0]:
spam_data.head()

class                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...