<a href="https://colab.research.google.com/github/agrawalsajal02/ML_workshop/blob/master/day_4_Copy_of_Embedding_layer_explanation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The notebook is written for a better understanding of the Embedding layer. How a sentence is given to the neural network model is explained step by step. 

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
cd /content/drive/My Drive/Phd_implementation/FDP_exp_2020/Day3

/content/drive/My Drive/Phd_implementation/FDP_exp_2020/Day3


In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np
from numpy import array
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Embedding, Dense
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [0]:
reviews = [
    'Never coming back!',
    'Horrible service',
    'Rude waitress',
    'Cold food.',
    'Horrible food!',
    'Awesome',
    'Awesome service!',
    'Rocks!',
    'poor work',
    'Couldn\'t have done better']

# Define labels (1=negative, 0=positive)
labels = array([1,1,1,1,1,0,0,0,0,0])

In [0]:
reviews

['Never coming back!',
 'Horrible service',
 'Rude waitress',
 'Cold food.',
 'Horrible food!',
 'Awesome',
 'Awesome service!',
 'Rocks!',
 'poor work',
 "Couldn't have done better"]

In [0]:
tokenizer = Tokenizer(lower= True)
tokenizer.fit_on_texts(reviews)


In [0]:
tokenizer.word_index

{'awesome': 4,
 'back': 7,
 'better': 17,
 'cold': 10,
 'coming': 6,
 "couldn't": 14,
 'done': 16,
 'food': 3,
 'have': 15,
 'horrible': 1,
 'never': 5,
 'poor': 12,
 'rocks': 11,
 'rude': 8,
 'service': 2,
 'waitress': 9,
 'work': 13}

In [0]:
VOCAB_SIZE = len(tokenizer.word_index)

In [0]:
VOCAB_SIZE

17

In [0]:
word_index = tokenizer.word_index

In [0]:
data_sequence = tokenizer.texts_to_sequences(reviews)

In [0]:
data_sequence

[[5, 6, 7],
 [1, 2],
 [8, 9],
 [10, 3],
 [1, 3],
 [4],
 [4, 2],
 [11],
 [12, 13],
 [14, 15, 16, 17]]

In [0]:
padded_reviews = pad_sequences(data_sequence, maxlen=4, padding='post')
print(padded_reviews)

[[ 5  6  7  0]
 [ 1  2  0  0]
 [ 8  9  0  0]
 [10  3  0  0]
 [ 1  3  0  0]
 [ 4  0  0  0]
 [ 4  2  0  0]
 [11  0  0  0]
 [12 13  0  0]
 [14 15 16 17]]


In [0]:
model = Sequential()
embedding_layer = Embedding(input_dim = VOCAB_SIZE+1, output_dim= 8, input_length=4)
model.add(embedding_layer)


In [0]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              144       
Total params: 144
Trainable params: 144
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
embedding_layer_weight = embedding_layer.get_weights()
embedding_layer_weight

[array([[ 0.03754839, -0.01140768,  0.01770461,  0.04112263, -0.01685237,
          0.0338383 , -0.03391452, -0.00789679],
        [ 0.03120956,  0.0468156 ,  0.03137118, -0.03447262, -0.00221352,
          0.03953988, -0.03042998, -0.03557882],
        [ 0.01556459, -0.03488901, -0.04846075,  0.01894421, -0.02828982,
         -0.04271015, -0.04923547,  0.0346146 ],
        [-0.01893415,  0.00939966, -0.00080925,  0.02643875, -0.02740996,
          0.0109603 ,  0.02903092,  0.04280638],
        [ 0.02069538, -0.00645801,  0.01021387, -0.02865515, -0.03872925,
          0.00639854,  0.03008026, -0.02871486],
        [ 0.03550676,  0.01159666, -0.01662052,  0.04219048,  0.02616277,
         -0.02120087, -0.02331743, -0.01782275],
        [-0.04229592,  0.00636043, -0.01371652, -0.0197389 , -0.01260028,
          0.02183018,  0.02069321,  0.02314886],
        [-0.00791813,  0.03559052, -0.03377806, -0.04331576,  0.00788231,
          0.0249253 , -0.03413322, -0.03084936],
        [-0.0342

In [0]:
embedding_layer_weight[0].shape

(18, 8)

In [0]:
#embedding_layer_weight[0][0]

In [0]:
pred = model.predict(padded_reviews)
pred


array([[[ 0.03550676,  0.01159666, -0.01662052,  0.04219048,
          0.02616277, -0.02120087, -0.02331743, -0.01782275],
        [-0.04229592,  0.00636043, -0.01371652, -0.0197389 ,
         -0.01260028,  0.02183018,  0.02069321,  0.02314886],
        [-0.00791813,  0.03559052, -0.03377806, -0.04331576,
          0.00788231,  0.0249253 , -0.03413322, -0.03084936],
        [ 0.03754839, -0.01140768,  0.01770461,  0.04112263,
         -0.01685237,  0.0338383 , -0.03391452, -0.00789679]],

       [[ 0.03120956,  0.0468156 ,  0.03137118, -0.03447262,
         -0.00221352,  0.03953988, -0.03042998, -0.03557882],
        [ 0.01556459, -0.03488901, -0.04846075,  0.01894421,
         -0.02828982, -0.04271015, -0.04923547,  0.0346146 ],
        [ 0.03754839, -0.01140768,  0.01770461,  0.04112263,
         -0.01685237,  0.0338383 , -0.03391452, -0.00789679],
        [ 0.03754839, -0.01140768,  0.01770461,  0.04112263,
         -0.01685237,  0.0338383 , -0.03391452, -0.00789679]],

       [[-0.

In [0]:
pred[0]

array([[ 0.03550676,  0.01159666, -0.01662052,  0.04219048,  0.02616277,
        -0.02120087, -0.02331743, -0.01782275],
       [-0.04229592,  0.00636043, -0.01371652, -0.0197389 , -0.01260028,
         0.02183018,  0.02069321,  0.02314886],
       [-0.00791813,  0.03559052, -0.03377806, -0.04331576,  0.00788231,
         0.0249253 , -0.03413322, -0.03084936],
       [ 0.03754839, -0.01140768,  0.01770461,  0.04112263, -0.01685237,
         0.0338383 , -0.03391452, -0.00789679]], dtype=float32)

In [0]:
padded_reviews[0]

array([5, 6, 7, 0], dtype=int32)

In [0]:
embedding_layer_weight[0][0]

array([ 0.03754839, -0.01140768,  0.01770461,  0.04112263, -0.01685237,
        0.0338383 , -0.03391452, -0.00789679], dtype=float32)

In [0]:
#load pre-trained embedding:
embeddings_index = {}
f = open('glove.twitter.27B.25d.txt', encoding="utf8")
for line in f:
    values = line.split()#This splits each values in a  line with spaces
    word = values[0] # This store the first values which is the word in english
    coefs = np.asarray(values[1:], dtype='float32') # This converts all splitted values from 1 to last(expect first word) into an array
    embeddings_index[word] = coefs # english word = array of numerical values
f.close()
print('Total %s word vectors in Glove 6B 100d.' % len(embeddings_index))

Total 1193514 word vectors in Glove 6B 100d.


In [0]:
# Initialize the weight for each word for the embedding layer. Words not present
# in the dictionary initialized by random value 
EMBEDDING_DIM = 25
embedding_matrix = np.random.random((len(word_index) + 1, EMBEDDING_DIM))
#embedding_matrix = (16433, 100) NOTE: It is from uniques words in our tweets
for word, i in word_index.items(): # Selecting word from our tweet unique words list for changing with the values from glove
    embedding_vector = embeddings_index.get(word) # Finding our tweet words in glove and taking its array of 100 values
    if embedding_vector is not None: 
#words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector


In [0]:
model = Sequential()
embedding_layer = Embedding(input_dim = VOCAB_SIZE+1, output_dim = 25, weights=[embedding_matrix], input_length=4, trainable = False)
model.add(embedding_layer)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 25)             450       
Total params: 450
Trainable params: 0
Non-trainable params: 450
_________________________________________________________________
None


In [0]:
embedding_layer_weight = embedding_layer.get_weights()
embedding_layer_weight

[array([[ 0.96450347,  0.6892435 ,  0.19204415,  0.63665587,  0.6144509 ,
          0.08198912,  0.34201977,  0.38128507,  0.14413469,  0.33028036,
          0.03865209,  0.290697  ,  0.2600713 ,  0.9479322 ,  0.7827116 ,
          0.18350631,  0.7477053 ,  0.2063826 ,  0.37889558,  0.14032003,
          0.24321668,  0.0787776 ,  0.32935488,  0.5474995 ,  0.8264487 ],
        [ 0.21438   , -0.66014   , -0.16823   ,  0.27111   ,  0.75163   ,
          1.4539    ,  1.3342    ,  0.45775   , -1.0655    , -0.43815   ,
         -0.3065    , -1.0593    , -3.0458    ,  0.15611   ,  1.9577    ,
          1.2217    ,  0.35779   ,  0.4452    , -0.34816   , -0.47898   ,
          0.62939   ,  0.82832   ,  0.74702   ,  0.15725   , -0.10929   ],
        [-0.30753   ,  0.88404   , -1.0297    , -0.61819   ,  1.0883    ,
         -0.51168   ,  0.20697   , -0.43241   ,  1.2657    ,  0.45289   ,
          0.51967   ,  0.050615  , -3.8389    ,  0.59332   ,  1.0632    ,
          0.32348   ,  0.85886   , -

In [0]:
embedding_layer_weight[0].shape

(18, 25)

In [0]:
pred_glove = model.predict(padded_reviews)
pred_glove

array([[[ 0.35787   ,  0.53172   ,  0.02891   , -0.11454   ,
         -0.9309    , -0.058475  ,  1.6786    , -0.26025   ,
         -0.79749   , -0.29905   , -0.049528  ,  0.37763   ,
         -5.4355    , -0.14486   , -0.4962    ,  0.98797   ,
          0.12834   , -0.033029  ,  0.52323   , -1.0346    ,
          0.55156   ,  0.7415    ,  0.20227   ,  0.67147   ,
          0.036255  ],
        [-0.72052   ,  0.77606   ,  0.58006   , -0.76466   ,
         -0.45005   , -0.21402   ,  1.5047    , -0.40918   ,
         -0.43951   , -0.14405   , -0.1272    ,  0.72284   ,
         -4.3729    ,  0.51053   ,  0.42036   ,  0.035156  ,
         -0.10893   , -0.75633   , -0.63182   , -0.35142   ,
         -0.31829   , -0.71342   ,  0.51693   ,  0.10108   ,
          0.48018   ],
        [-0.74355   ,  0.715     , -0.1593    , -0.28136   ,
         -0.736     , -0.17702   ,  1.0432    ,  0.62863   ,
         -1.0324    ,  0.44264   , -0.11356   ,  0.30086   ,
         -4.7917    , -0.22962   , -0.2

In [0]:
pred_glove[0]

array([[ 0.35787   ,  0.53172   ,  0.02891   , -0.11454   , -0.9309    ,
        -0.058475  ,  1.6786    , -0.26025   , -0.79749   , -0.29905   ,
        -0.049528  ,  0.37763   , -5.4355    , -0.14486   , -0.4962    ,
         0.98797   ,  0.12834   , -0.033029  ,  0.52323   , -1.0346    ,
         0.55156   ,  0.7415    ,  0.20227   ,  0.67147   ,  0.036255  ],
       [-0.72052   ,  0.77606   ,  0.58006   , -0.76466   , -0.45005   ,
        -0.21402   ,  1.5047    , -0.40918   , -0.43951   , -0.14405   ,
        -0.1272    ,  0.72284   , -4.3729    ,  0.51053   ,  0.42036   ,
         0.035156  , -0.10893   , -0.75633   , -0.63182   , -0.35142   ,
        -0.31829   , -0.71342   ,  0.51693   ,  0.10108   ,  0.48018   ],
       [-0.74355   ,  0.715     , -0.1593    , -0.28136   , -0.736     ,
        -0.17702   ,  1.0432    ,  0.62863   , -1.0324    ,  0.44264   ,
        -0.11356   ,  0.30086   , -4.7917    , -0.22962   , -0.21154   ,
        -0.14965   , -0.31582   , -1.3908    , -0

In [0]:
never 0.35787 0.53172 0.02891 -0.11454 -0.9309 -0.058475 1.6786 -0.26025 -0.79749 -0.29905 -0.049528 0.37763 -5.4355 -0.14486 -0.4962 0.98797 0.12834 -0.033029 0.52323 -1.0346 0.55156 0.7415 0.20227 0.67147 0.036255


In [0]:
never 0.35787 0.53172 0.02891 -0.11454 -0.9309 -0.058475 1.6786 -0.26025 -0.79749 -0.29905 -0.049528 0.37763 -5.4355 -0.14486 -0.4962 0.98797 0.12834 -0.033029 0.52323 -1.0346 0.55156 0.7415 0.20227 0.67147 0.036255

