<a href="https://colab.research.google.com/github/agrawalsajal02/ML_workshop/blob/master/workshop3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd


In [0]:
file=pd.read_csv("/content/SMSSpamCollection",sep="/t",names=["label","text"])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [0]:
text=["today is valentine day today","today is a black day"]
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))
np=cv.fit_transform(text)
np

<2x11 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [0]:
cv.get_feature_names()

['black',
 'black day',
 'day',
 'day today',
 'is',
 'is black',
 'is valentine',
 'today',
 'today is',
 'valentine',
 'valentine day']

In [0]:
np=np.toarray()

In [0]:
np

array([[0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0]])

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()


In [0]:
fl=tfidf.fit_transform(text).toarray()

In [0]:
fl

array([[0.        , 0.35409974, 0.35409974, 0.70819948, 0.49767483],
       [0.63009934, 0.44832087, 0.44832087, 0.44832087, 0.        ]])

In [0]:
print(tfidf.get_feature_names())

['black', 'day', 'is', 'today', 'valentine']


LookupError: ignored

In [0]:
exp=["today is al-ml workshop"]

In [0]:
exp_y=tfidf.transform(exp)

In [0]:
exp_y.toarray()

array([[0.        , 0.        , 0.70710678, 0.70710678, 0.        ]])

In [0]:
tfidf.get_feature_names()

['black', 'day', 'is', 'today', 'valentine']

In [0]:
import pandas as pd

In [0]:
file=pd.read_csv("/content/amazon_cells_labelled.txt",sep="\t",names=["text","label"])

In [21]:
file.head()

text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1

In [22]:
type(file)

pandas.core.frame.DataFrame

In [0]:
import nltk
import re

In [24]:
sentence=nltk.sent_tokenizer(file)

AttributeError: ignored

In [0]:
data_text=file["text"]
data_label=file["label"]

In [26]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [0]:
stop=set(stopwords.words("english"))

In [28]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [29]:
data_text

0      So there is no way for me to plug it in here i...
1                            Good case, Excellent value.
2                                 Great for the jawbone.
3      Tied to charger for conversations lasting more...
4                                      The mic is great.
                             ...                        
995    The screen does get smudged easily because it ...
996    What a piece of junk.. I lose more calls on th...
997                         Item Does Not Match Picture.
998    The only thing that disappoint me is the infra...
999    You can not answer calls with the unit, never ...
Name: text, Length: 1000, dtype: object

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test=train_test_split(data_text,data_label,test_size=0.3,random_state=42)

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(ngram_range=(1,3))
x_train_sent=tf.fit_transform(x_train)
x_test_sent=tf.transform(x_test)

In [0]:
###########################workshop   3 da ##########################################333

In [0]:
from sklearn.tree import DecisionTreeClassifier
decision_tree=DecisionTreeClassifier()
decision_tree.fit(x_train_sent,y_train)
y_pred=decision_tree.predict(x_test_sent)

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.6666666666666666


In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[122  24]
 [ 76  78]]


In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.62      0.84      0.71       146
           1       0.76      0.51      0.61       154

    accuracy                           0.67       300
   macro avg       0.69      0.67      0.66       300
weighted avg       0.69      0.67      0.66       300



In [0]:
######################################################################

In [0]:
######  workshop 4 #####################################################

In [38]:
x_train_sent.shape

(700, 11051)