<a href="https://colab.research.google.com/github/agrawalsajal02/ML_workshop/blob/master/workshop4_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
###                 Dense  neural network  ######################
import pandas as pd

In [0]:
file=pd.read_csv("/content/amazon_cells_labelled.txt",sep="\t",names=["text","label"])

In [6]:
file.head(5)

text  label
0  So there is no way for me to plug it in here i...      0
1                        Good case, Excellent value.      1
2                             Great for the jawbone.      1
3  Tied to charger for conversations lasting more...      0
4                                  The mic is great.      1

In [0]:
data_text=file["text"]
data_label=file["label"]

In [9]:
data_text

0      So there is no way for me to plug it in here i...
1                            Good case, Excellent value.
2                                 Great for the jawbone.
3      Tied to charger for conversations lasting more...
4                                      The mic is great.
                             ...                        
995    The screen does get smudged easily because it ...
996    What a piece of junk.. I lose more calls on th...
997                         Item Does Not Match Picture.
998    The only thing that disappoint me is the infra...
999    You can not answer calls with the unit, never ...
Name: text, Length: 1000, dtype: object

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data_text,data_label,random_state=42,test_size=0.3)

In [15]:
x_train.shape

(700,)

In [16]:
y_train.shape

(700,)

In [0]:


from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(ngram_range=(1,3))

In [0]:
x_train_sent=tf.fit_transform(x_train)
x_test_sent=tf.transform(x_test)

In [27]:
x_train_sent.shape

(700, 11051)

In [0]:
import numpy as np
from keras.utils.np_utils import to_categorical
label_train=to_categorical(y_train)
label_test=to_categorical(y_test)

In [24]:
label_train

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [25]:
from keras.layers import Dense,Activation
from keras.models import Sequential
model=Sequential()

In [26]:
model.add(Dense(512,input_dim=11051,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(2,activation="softmax"))
model.summary()



Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               5658624   
_________________________________________________________________
dense_2 (Dense)              (None, 64)                32832     
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 130       
Total params: 5,691,586
Trainable params: 5,691,586
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [35]:
model.fit(x_train_sent,label_train,validation_data=(x_test_sent,label_test),epochs=10,batch_size=50,verbose=2)

Train on 700 samples, validate on 300 samples
Epoch 1/10





 - 3s - loss: 0.6867 - acc: 0.5257 - val_loss: 0.6563 - val_acc: 0.7733
Epoch 2/10
 - 1s - loss: 0.5033 - acc: 0.9929 - val_loss: 0.5161 - val_acc: 0.7733
Epoch 3/10
 - 1s - loss: 0.1559 - acc: 1.0000 - val_loss: 0.3792 - val_acc: 0.8367
Epoch 4/10
 - 1s - loss: 0.0142 - acc: 1.0000 - val_loss: 0.4120 - val_acc: 0.8333
Epoch 5/10
 - 1s - loss: 0.0020 - acc: 1.0000 - val_loss: 0.4430 - val_acc: 0.8333
Epoch 6/10
 - 1s - loss: 8.6376e-04 - acc: 1.0000 - val_loss: 0.4549 - val_acc: 0.8333
Epoch 7/10
 - 1s - loss: 5.7418e-04 - acc: 1.0000 - val_loss: 0.4607 - val_acc: 0.8300
Epoch 8/10
 - 1s - loss: 4.5444e-04 - acc: 1.0000 - val_loss: 0.4650 - val_acc: 0.8333
Epoch 9/10
 - 1s - loss: 3.7776e-04 - acc: 1.0000 - val_loss: 0.4687 - val_acc: 0.8300
Epoch 10/10
 - 1s - loss: 3.2513e-04 - acc: 1.0000 - val_loss: 0.4718 - val_acc: 0.8300


In [43]:
y_predict=model.predict(x_test_sent)
y_predict.shape

(300, 2)

In [0]:
pred=np.zeros_like(y_predict)
pred[np.arange(len(y_predict)),y_predict.argmax(1)]=1

In [49]:
pred

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [0]:
from sklearn.metrics import classification_report

In [53]:
print(classification_report(label_test,pred))

              precision    recall  f1-score   support

           0       0.81      0.86      0.83       146
           1       0.86      0.81      0.83       154

   micro avg       0.83      0.83      0.83       300
   macro avg       0.83      0.83      0.83       300
weighted avg       0.83      0.83      0.83       300
 samples avg       0.83      0.83      0.83       300



In [59]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(pred.argmax(axis=1),label_test.argmax(axis=1)))

[[125  30]
 [ 21 124]]


In [60]:
from sklearn.metrics import accuracy_score
print(accuracy_score(pred,label_test))

0.83


In [0]:
#################################################################33
#####################################################################
#####################################################################\

#########    HERE START WORD EMBEDDING    ############################

In [0]:
###########         Word Embedding    #####################

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np
from numpy import array


In [0]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [0]:
from tensorflow.keras.layers import Flatten,Embedding,Dense
from keras.preprocessing.text import Tokenizer


In [0]:
reviews=[
          'Never coming back!',
    'Horrible service',
    'Rude waitress',
    'Cold food.',
    'Horrible food!',
    'Awesome',
    'Awesome service!',
    'Rocks!',
    'poor work',
    'Couldn\'t have done better'
]
labels = array([1,1,1,1,1,0,0,0,0,0])

In [82]:
reviews

['Never coming back!',
 'Horrible service',
 'Rude waitress',
 'Cold food.',
 'Horrible food!',
 'Awesome',
 'Awesome service!',
 'Rocks!',
 'poor work',
 "Couldn't have done better"]

In [0]:
tokenizer=Tokenizer(lower=True)
tokenizer.fit_on_texts(reviews)

In [84]:
tokenizer.word_index

{'awesome': 4,
 'back': 7,
 'better': 17,
 'cold': 10,
 'coming': 6,
 "couldn't": 14,
 'done': 16,
 'food': 3,
 'have': 15,
 'horrible': 1,
 'never': 5,
 'poor': 12,
 'rocks': 11,
 'rude': 8,
 'service': 2,
 'waitress': 9,
 'work': 13}

In [0]:
vocabsize=len(tokenizer.word_index)

In [0]:
data_sequence=tokenizer.texts_to_sequences(reviews)

In [87]:
data_sequence

[[5, 6, 7],
 [1, 2],
 [8, 9],
 [10, 3],
 [1, 3],
 [4],
 [4, 2],
 [11],
 [12, 13],
 [14, 15, 16, 17]]

In [89]:
padded_reviews=pad_sequences(data_sequence,maxlen=4,padding="post")
padded_reviews

array([[ 5,  6,  7,  0],
       [ 1,  2,  0,  0],
       [ 8,  9,  0,  0],
       [10,  3,  0,  0],
       [ 1,  3,  0,  0],
       [ 4,  0,  0,  0],
       [ 4,  2,  0,  0],
       [11,  0,  0,  0],
       [12, 13,  0,  0],
       [14, 15, 16, 17]], dtype=int32)

In [0]:
model=Sequential()
embedding_layer=Embedding(input_dim=vocabsize+1,output_dim=8,input_length=4)
model.add(embedding_layer)

In [120]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 8)              144       
Total params: 144
Trainable params: 144
Non-trainable params: 0
_________________________________________________________________
None


In [121]:
embedding_layer_weight=embedding_layer.get_weights()
embedding_layer_weight[0][0]

array([-0.03049186, -0.03291543,  0.00185764, -0.02640482,  0.02252835,
        0.03463932, -0.04186488, -0.01477962], dtype=float32)

In [123]:
pred=model.predict(padded_reviews)
pred[0]

array([[-0.04812574,  0.00255276, -0.0308069 , -0.03352361,  0.02993406,
         0.04319109, -0.03674222, -0.02778462],
       [-0.0134142 , -0.04217116, -0.0441142 , -0.02482749,  0.01438928,
         0.04103327,  0.01969641, -0.00350431],
       [-0.04659962,  0.03498275, -0.04440835,  0.02262551, -0.00561393,
         0.00669925,  0.00686111, -0.01218239],
       [-0.03049186, -0.03291543,  0.00285764, -0.02640482,  0.02352835,
         0.03563932, -0.04186488, -0.01477962]], dtype=float32)

In [111]:
padded_reviews

array([[ 5,  6,  7,  0],
       [ 1,  2,  0,  0],
       [ 8,  9,  0,  0],
       [10,  3,  0,  0],
       [ 1,  3,  0,  0],
       [ 4,  0,  0,  0],
       [ 4,  2,  0,  0],
       [11,  0,  0,  0],
       [12, 13,  0,  0],
       [14, 15, 16, 17]], dtype=int32)

In [117]:
embedding_layer_weight[0][5]

array([-0.02471867,  0.00856201,  0.01780063, -0.0493264 , -0.00997846,
       -0.00636498, -0.04189712,  0.02737634], dtype=float32)

In [0]:
###################    embedding   in amazon classification ##############3

In [0]:
import pandas as pd

In [0]:
data=pd.read_csv("/content/amazon_cells_labelled.txt",sep="\t",names=["text","label"])

In [0]:
text=data["text"]
class_label=data["label"]

In [131]:
text.shape

(1000,)

In [132]:
class_label.shape

(1000,)

In [0]:
import numpy as np
from keras.utils.np_utils import to_categorical
label=to_categorical(np.array(class_label))

In [142]:
label

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
from keras.preprocessing.text import Tokenizer
tk=Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',lower=True, split=" ")
tk.fit_on_texts(text)

In [0]:
index=tk.word_index

In [0]:
x=tk.texts_to_sequences(text)

In [153]:
x

[[33,
  117,
  5,
  53,
  214,
  11,
  47,
  8,
  155,
  4,
  19,
  337,
  19,
  1,
  546,
  416,
  2,
  241,
  190,
  6,
  812],
 [21, 48, 54, 272],
 [16, 11, 1, 417],
 [813, 8, 83, 11, 418, 547, 84, 50, 814, 242, 815, 144],
 [1, 338, 5, 16],
 [2, 22, 8, 816, 1, 155, 8, 70, 4, 8, 273, 55, 145, 8, 70, 339, 146],
 [49,
  23,
  22,
  215,
  817,
  65,
  215,
  818,
  419,
  100,
  819,
  1,
  820,
  12,
  340,
  821,
  12,
  130,
  36,
  190,
  36],
 [49, 23, 34, 274, 822, 23, 341, 22, 7],
 [823, 8, 216, 2, 548, 10, 85],
 [101, 6, 118, 12, 85, 3, 56],
 [3, 1, 32, 25, 5, 16],
 [549, 17, 15, 173, 71, 243, 43, 1, 275, 29, 8, 1, 550, 29],
 [49,
  1,
  119,
  342,
  824,
  190,
  6,
  825,
  174,
  826,
  2,
  276,
  8,
  551,
  827,
  420,
  3,
  828,
  32,
  43,
  1,
  27],
 [15, 21, 25, 421],
 [1, 156, 5, 15, 829, 31, 1, 39, 343, 5, 13, 15, 102, 64, 37],
 [175, 60, 11, 77, 36, 422, 40, 6, 344, 552, 9],
 [2, 553, 423, 86, 13, 46, 830],
 [33, 131, 33, 21],
 [28, 16],
 [4, 831, 161, 345, 19, 

In [0]:
vocab_size=len(index)

In [155]:
print(vocab_size+1)

1879


In [159]:
from keras.preprocessing.sequence import pad_sequences
embedding_vector_length=32
padded_docs=pad_sequences(x,maxlen=embedding_vector_length,padding="post")
print (padded_docs[0].shape)

(32,)


In [0]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation,Flatten
from kaeras.layers import Embedding